### ISSUE TITLE
[BUG] Updating related entity completely remove parent entity

### ISSUE THREAD

**Issue by brud** [leonardoporro/Detached-Mapper#38]
### Description
If I try to update `Modification` entity without relation fields - all fine.
But if I pass collection of `Option` - I have an exception and my existing `Modification` record in DB are gone.
Also I've tried to add `[Aggregate]` or `[Composition]` to `Options` field and add to `MapAsync` in controller second parameter with `new MapperParameters { AggregationAction = AggregationAction.Map}` - result the same...

### Steps to reproduce
1. In a Startup.cs
```
        services
                .AddControllers()
                .AddNewtonsoftJson(o =>
                {
                    ...
                    o.SerializerSettings.Converters.Add(new PatchJsonConverter(new AnnotationPatchTypeInfoProvider()));
                })
```
2. Models
```
    [UsePatch]
    public class Modification : IHasId
    {
        public virtual int Id { get; set; }
        ...
        public virtual List<Option>? Options { get; set; }
        ...
    }

    [UsePatch]
     public class Option : IHasId
     {
        public virtual int Id { get; set; }
        public virtual string Value { get; set; }
        public virtual int ModificationId { get; set; }
     }
```

### My env:
net5.0
ef core 5.0.10
npgsql 5.0.10
Detached-Mapper 5.0.22
Detached-PatchTypes 5.0.2

### Exception
```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at magazine.Controllers.OData.ModificationController.Patch(Modification modification, CancellationToken ctx) in D:\projects\magazine\magazine\Controllers\OData\ModificationController.cs:line 57
   at lambda_method630(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by leonardoporro** [comment]
I've been doing lot of testing on this, it seems that the foreing key defaults to 0 which ends in parent removal.
Unmap the Id seemed to work for me, but also prevents me to update the entity using the fk.
A better option could be to use a DTO, I mainly designed this library to do that. So the DTO will contain the properties you want to update, with no parents or foreing keys.
I'm very short in time, if no workaround works for you, would you consider adding some integration tests, like [these](https://github.com/leonardoporro/Detached-Mapper/blob/main/test/Detached.Mappers.EntityFramework.Tests/MapEntityNoKeyTest.cs)?
It would be really helpful and save me some time.

**Comment by leonardoporro** [comment]
I've re written the entire mapping engine and improving parent detection using a stack of previously mapped objects
now parents must be marked with [Parent] decorator and are updated, disregarding if they exist in the DTO or not.
