### ISSUE TITLE
context disposed in MapAsync

### ISSUE THREAD

**Issue by cederron** [leonardoporro/Detached-Mapper#74]
Call to MapAsync gives me a context disposed exception 'System.ObjectDisposedException: 'Cannot access a disposed context instance'.

```
at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at Detached.Mappers.EntityFramework.EFMapContext.TrackChange[TTarget,TSource,TKey](TTarget entity, TSource source, TKey key, MapperActionType actionType) in D:\Nextcloud\Programacion\MisCodigos\ZsaLobApiMVC\Detached-Mapper-main\src\Detached.Mappers.EntityFramework\EFMapContext.cs:line 31
   at Detached.Mappers.TypeMappers.Entity.Complex.RootEntityTypeMapper`3.Map(TSource source, TTarget target, IMapContext context) in D:\Nextcloud\Programacion\MisCodigos\ZsaLobApiMVC\Detached-Mapper-main\src\Detached.Mappers\TypeMappers\Entity\Complex\RootEntityTypeMapper.cs:line 36
   at Detached.Mappers.TypeMappers.TypeMapper`2.Map(Object source, Object target, IMapContext context) in D:\Nextcloud\Programacion\MisCodigos\ZsaLobApiMVC\Detached-Mapper-main\src\Detached.Mappers\TypeMappers\TypeMapper.cs:line 11
   at Detached.Mappers.Mapper.Map(Object source, Type sourceClrType, Object target, Type targetClrType, IMapContext context) in D:\Nextcloud\Programacion\MisCodigos\ZsaLobApiMVC\Detached-Mapper-main\src\Detached.Mappers\Mapper.cs:line 46
   at Detached.Mappers.EntityFramework.EFMapper.Map[TEntity](DbContext dbContext, Object entityOrDTO, MapParameters parameters) in D:\Nextcloud\Programacion\MisCodigos\ZsaLobApiMVC\Detached-Mapper-main\src\Detached.Mappers.EntityFramework\EFMapper.cs:line 82
   at Detached.Mappers.EntityFramework.EFMapper.<>c__DisplayClass8_0`1.<MapAsync>b__0() in D:\Nextcloud\Programacion\MisCodigos\ZsaLobApiMVC\Detached-Mapper-main\src\Detached.Mappers.EntityFramework\EFMapper.cs:line 67
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

```c#
builder.Services.AddDbContext<ApplicationDbContext>(options => 
    options.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString))
    .UseDetached());
```

```c#
    public class ApplicationDbContext : IdentityDbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public DbSet<Contacto> Contactos { get; set; }
        public DbSet<ContactoTipo> ContactoTipos { get; set; }

    }
```

```c#
    [Route("api/[controller]")]
    [ApiController]
    public class ContactosController : ControllerBase
    {
        ApplicationDbContext _context; 

        public ContactosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // PUT api/<ContactosController>/5
        [HttpPut("{id}")]
        public async void Put(int id, [FromBody] AddUpdateContactoDTO value)
        {
                var entity = await _context.MapAsync<Contacto>(value);
                await _context.SaveChangesAsync();
        }
    }
}

```

I'm using .Net Core 7 , And Pomelo MySql adapter for context.
Any idea what could be wrong ?

**Comment by cederron** [comment]
Ok, so the problem was the return type in the controller method 'async void', i changed to 'async Task' and the exception went away.
However, now the entity is being deleted from the database, instead of being updated, the dto has an id wich is being mapped fine, dont know whats happening.

**Comment by leonardoporro** [comment]
still working on this? 
would you be able to provide a minimum application or a PR with a test to reproduce the issue?

**Comment by leonardoporro** [comment]
please reopen it if you can provide more data to reproduce the issue
and thanks for trying
