### ISSUE TITLE
No factory for Optional<Guid?> -> Guid

### ISSUE THREAD

**Issue by furier** [leonardoporro/Detached-Mapper#75]
Hi

I am trying to map [HotChocolate input types](https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/input-object-types/#optional-properties) to entities and get this error, and could not find anything in the wiki on how to do this.

Here are example classes for DTO and Entity
```cs
public partial class CreateProjectDto
{
    public Optional<Guid?> Id { get; set; }
    public string Name { get; set; }
}

public class Project 
{
    public Guid Id { get; set; }
    public string Name { get; set; };
}
```

Running the following code generates an exception

```cs
var project = await dbContext.MapAsync<Project>(dto);
```

Exception
```cs
Detached.Mappers.Exceptions.MapperException: No factory for Optional<Guid?> -> Guid
   at Detached.Mappers.Mapper.<>c__DisplayClass9_0.<GetTypeMapper>b__0(TypePairKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Detached.Mappers.Mapper.GetTypeMapper(TypePair typePair)
   at Detached.Mappers.TypeMappers.ExpressionBuilder.BuildGetKeyExpressions(TypePair typePair, LambdaExpression& getSourceKeyExpr, LambdaExpression& getTargetKeyExpr, Type& keyType)
   at Detached.Mappers.TypeMappers.Entity.Complex.EntityTypeMapperFactory.Create(Mapper mapper, TypePair typePair)
   at Detached.Mappers.Mapper.<>c__DisplayClass9_0.<GetTypeMapper>b__0(TypePairKey key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Detached.Mappers.Mapper.GetTypeMapper(TypePair typePair)
   at Detached.Mappers.Mapper.Map(Object source, Type sourceClrType, Object target, Type targetClrType, IMapContext context)
   at Detached.Mappers.EntityFramework.EFMapper.Map[TEntity](DbContext dbContext, Object entityOrDTO, MapParameters parameters)
   at Detached.Mappers.EntityFramework.EFMapper.<>c__DisplayClass8_0`1.<MapAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Gateway.API.Mutations.ProjectMutations.CreateProjects(GatewayDbContext gatewayDbContext, CreateProjectDto[] dtos, CancellationToken cancellationToken) in C:\dev\Connected\src\Gateway\Gateway.API\Mutations\ProjectMutations.cs:line 21
```

**Comment by furier** [comment]
I am playing around with implementing a `TypeMapperFactory` and `TypeMapper`

```cs
public class OptionalTypeMapperFactory : ITypeMapperFactory
{
    public bool CanCreate(Mapper mapper, TypePair typePair)
    {
        var canCreate = typePair.SourceType.IsComplex() &&
                        typeof(IOptional).IsAssignableFrom(typePair.SourceType.ClrType) &&
                        typePair.TargetType.IsPrimitive();

        return canCreate;
    }

    public ITypeMapper Create(Mapper mapper, TypePair typePair) =>
        (ITypeMapper) Activator.CreateInstance(typeof (OptionalTypeMapper<,>).MakeGenericType(typePair.SourceType.ClrType, typePair.TargetType.ClrType))!;
}

public class OptionalTypeMapper<TSource, TTarget> : TypeMapper<TSource, TTarget>
{
    private readonly PropertyInfo _isEmptyProperty;
    private readonly PropertyInfo _valueProperty;

    public OptionalTypeMapper()
    {
        var type = typeof(TSource);
        _isEmptyProperty = type.GetProperty("IsEmpty")!;
        _valueProperty = type.GetProperty("Value")!;
    }

    public override TTarget Map(TSource source, TTarget target, IMapContext context)
    {
        if (source is null || _isEmptyProperty.GetValue(source) is true)
            return target;
        
        var value = _valueProperty.GetValue(source);

        return (TTarget) Convert.ChangeType(value, typeof(TTarget))!;
    }
}
```

but still getting into trouble...

```cs
System.InvalidOperationException: No coercion operator is defined between types 'HotChocolate.Optional`1[System.Nullable`1[System.Guid]]' and 'System.Guid'.
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type)
   at Detached.Mappers.EntityFramework.Queries.QueryProvider.CreateFilterExpression[TSource,TTarget](TypePair typePair, ConstantExpression sourceConstant)
   at Detached.Mappers.EntityFramework.Queries.QueryProvider.<GetTemplate>b__6_0[TSource,TTarget](QueryCacheKey fn)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Detached.Mappers.EntityFramework.Queries.QueryProvider.GetTemplate[TSource,TTarget]()
   at Detached.Mappers.EntityFramework.Queries.QueryProvider.Load[TSource,TTarget](IQueryable`1 queryable, TSource source)
   at Detached.Mappers.EntityFramework.EFMapContext.TrackChange[TTarget,TSource,TKey](TTarget entity, TSource source, TKey key, MapperActionType actionType)
   at Detached.Mappers.TypeMappers.Entity.Complex.RootEntityTypeMapper`3.Map(TSource source, TTarget target, IMapContext context)
   at Detached.Mappers.TypeMappers.TypeMapper`2.Map(Object source, Object target, IMapContext context)
   at Detached.Mappers.Mapper.Map(Object source, Type sourceClrType, Object target, Type targetClrType, IMapContext context)
   at Detached.Mappers.EntityFramework.EFMapper.Map[TEntity](DbContext dbContext, Object entityOrDTO, MapParameters parameters)
   at Detached.Mappers.EntityFramework.EFMapper.<>c__DisplayClass8_0`1.<MapAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Gateway.API.Mutations.ProjectMutations.CreateProjects(GatewayDbContext gatewayDbContext, CreateProjectDto[] dtos, CancellationToken cancellationToken) in C:\dev\Connected\src\Gateway\Gateway.API\Mutations\ProjectMutations.cs:line 21
```

**Comment by leonardoporro** [comment]
@furier Hi, thanks for the interest in the library, and good for trying to write the mappers!
Adding support for hot chocolate makes sense. Unfortunately I'm sick now, but I can try something next weekend If I feel better
And yes, the wiki needs more work it's not 100 % completed

**Comment by furier** [comment]
The mapper appears to function properly; however, the issue arises when the library attempts to query for existing entities and tries to extract the key from the DTOs Id property, which is of type Optional<T>. It is unable to coerce this into the appropriate type for the entity's Id property.

**Comment by leonardoporro** [comment]
Mmm.. in that case, we need to be sure that there is a factory mapper between T and Optional<T> that works in two ways
The mapper tries to convert Id types of it doesn't match
P

**Comment by furier** [comment]
First of all, I hope you get well soon! Your health is the most important thing right now, so please take your time to recover.

I appreciate your feedback and the opportunity to contribute to the library. Regarding the addition of this code, I was wondering if you think it would be more appropriate to include this functionality as part of the main library or as a separate NuGet package? This way, users could choose to add support for HotChocolate if needed, without affecting those who don't require it.

Please let me know your thoughts on this when you're feeling better, and there's absolutely no rush. Your well-being comes first.

Take care and get well soon!

**Comment by leonardoporro** [comment]
@furier thanks for your kind message!

Yup, Detached.Mappers.HotChocolate makes sense, to keep core clean of references.
You are welcome to put it in this repo with your name in the copyright of the project, or in your own repo.
(I can approve the pr or give you more access)
Having the code and tests over there makes easier for me to take a look if there are bugs.
And, there is a Partial Updates page in the wiki, it was meant to describe dtos, Ipatch and Optional fits perfectly there
I can add docs later with the proper credits to you in the wiki and main readme.

**Comment by leonardoporro** [comment]
@furier Did this work? do you need any extra help?
Also, are you planning to push something about Optional<>? Otherwise I'll create a ticket to implement it later
Thanks

**Comment by furier** [comment]
@leonardoporro it currently seem to work, have not picked up any issues with it yet. 

however as mentioned before I did convert my DTOs `Id` property to no longer be "nullable" with the `?` operator but are still nullable because they are wrapped in the `Optional<T>` type. It just has to do with the hotchocolate schema inference, that at least in previous versions it would label types wrapped in optional as not optional without the `?` operator, but seems like they have fixed that in later versions.

I was planning on pushing some changes but right now I have to much going on privately and at work, I am just swamped. I am sorry, id like to contribute... but it will have to wait.

**Comment by furier** [comment]
Added a PR #78

**Comment by leonardoporro** [comment]
@furier Awesome, thank you!

I found an issue, that is probably also the the cause of your Optional<Nullable<T>>.

When mapping Optional<T1> to Optional<T2> a recursive mapping from T1 to T2 is needed, even if T1 and T2 are of the same type.

[NullableTypeMapper](https://github.com/leonardoporro/Detached-Mapper/blob/main/src/Detached.Mappers/TypeMappers/POCO/Nullable/NullableTypeMapper.cs) is doing that...

For nullable types,  there won't be a ton of issues if you let the system cast or convert types, but in your case, Optional<T> when T is an entity will fail, because the mapper copies the values from a DTO (can be the same entity or not) to an already attached entity. 

The conversion will fail if T1 and T2 are different, or SaveChangesAsync will fail because the entity state will be detached.

Anyway, awesome contribution! I love it. If you make an update let me know otherwise I will do the fix later.

And I'll probably have to move your code to a new project to remove HotChocolate reference from the core mapper library (as you already mentioned before)

Thanks!

**Comment by leonardoporro** [comment]
Released https://www.nuget.org/packages/Detached.Mappers.HotChocolate/7.0.1
more work is needed anyway...

**Comment by leonardoporro** [comment]
credits

https://github.com/leonardoporro/Detached-Mapper/wiki/Partial-Updates
